-- OT Calculator initial schema
-- Apply this in the Supabase SQL editor or via the Supabase CLI.

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table public.ot_records (
  id bigint generated by default as identity primary key,
  work_date date not null unique,
  end_time time not null,
  ot_minutes integer not null default 0,
  ot_amount numeric(10, 2) not null default 0,
  note text,
  day_kind text not null default 'ot',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint ot_records_ot_minutes_nonnegative check (ot_minutes >= 0),
  constraint ot_records_ot_amount_nonnegative check (ot_amount >= 0),
  constraint ot_records_day_kind_valid check (day_kind in ('ot', 'off', 'absent'))
);

-- work_date is unique, so lookups are already indexed.
-- No extra ot_records_work_date_idx to avoid a duplicate index.

create trigger ot_records_set_updated_at
before update on public.ot_records
for each row
execute procedure public.set_updated_at();

create table public.app_settings (
  id integer primary key default 1,
  hourly_rate numeric(10, 2) not null default 75,
  normal_end_time time not null default '17:00',
  period_start_day integer not null default 26,
  period_end_day integer not null default 26,
  cycle_goal_amount numeric(10, 2) not null default 0,
  updated_at timestamptz not null default now(),
  constraint app_settings_single_row check (id = 1),
  constraint app_settings_hourly_rate_nonnegative check (hourly_rate >= 0),
  constraint app_settings_period_start_day_range check (period_start_day between 1 and 31),
  constraint app_settings_period_end_day_range check (period_end_day between 1 and 31),
  constraint app_settings_cycle_goal_nonnegative check (cycle_goal_amount >= 0)
);

create trigger app_settings_set_updated_at
before update on public.app_settings
for each row
execute procedure public.set_updated_at();

insert into public.app_settings (id, hourly_rate, normal_end_time)
values (1, 75, '17:00')
on conflict (id) do nothing;

create table public.saved_themes (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  config jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint saved_themes_name_not_blank check (char_length(trim(name)) > 0)
);

create trigger saved_themes_set_updated_at
before update on public.saved_themes
for each row
execute procedure public.set_updated_at();

-- RLS is enabled with no policies for anon/authenticated.
-- All application access goes through Next.js server code using the
-- service-role key, which bypasses RLS. The public/publishable key
-- cannot read or write these tables.
alter table public.ot_records enable row level security;
alter table public.app_settings enable row level security;
alter table public.saved_themes enable row level security;

revoke all on table public.ot_records from anon, authenticated;
revoke all on table public.app_settings from anon, authenticated;
revoke all on table public.saved_themes from anon, authenticated;

grant all on table public.ot_records to service_role;
grant all on table public.app_settings to service_role;
grant all on table public.saved_themes to service_role;
